services:
    accounts:
      image: siddhantkadam/accounts:v1
      container_name: accounts-ms
      ports:
      - "8081:8081"
      deploy:
        resources:
         limits:
          memory: 800m
      networks:
      - NSKBank

    loans:
      image: siddhantkadam/loans:v1
      container_name: loans-ms
      ports:
      - "8082:8082"
      deploy:
        resources:
          limits:
            memory: 800m
      networks:
      - NSKBank

    cards:
      image: siddhantkadam/cards:v1
      container_name: cards-ms
      ports:
        - "8083:8083"
      deploy:
        resources:
          limits:
            memory: 800m
      networks:
      - NSKBank

networks:
  NSKBank:
    driver: "bridge"