spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: SpringBoot_CustomerAccount
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/account/*

          - id: SpringBoot_Cards
            uri: http://localhost:8082
            predicates:
              - Path=/api/v2/cards/*

          - id: SpringBoot_CustomerLoans
            uri: http://localhost:8083
            predicates:
              - Path=/api/v3/loans/*